# Generated by Django 4.1.3 on 2022-12-01 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_auto_20210926_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=500)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('password', models.CharField(db_index=True, max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_set', to='core_user.method')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
